version: "3.9"

services:
  database:
    image: postgres
    environment:
      PGUSER: "${POSTGRES_USER}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 10

  balance:
    image: avito-balance-service
    build:
      context: ./
      dockerfile: ./build/multistage.Dockerfile
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8080:8080"